### ISSUE TITLE
XSS Vulnerability in ManageableList

### ISSUE THREAD

**Issue by Addono** [Synerise/synerise-design#1]
Any user who can control the content of a manageable list can inject arbitrary code into the browser.
![image](https://user-images.githubusercontent.com/15435678/76426172-f9842a80-63aa-11ea-89a3-430eecec6152.png)

![image](https://user-images.githubusercontent.com/15435678/76426226-0e60be00-63ab-11ea-9a3d-4e5a1cc4e075.png)

https://github.com/Synerise/synerise-design/blob/a2aa647281039ea291846e90cf42545f6ec6296e/packages/components/manageable-list/src/Item/ItemName/ItemName.tsx#L57

**Comment by ofsajd** [comment]
Hi, thanks for your feedback. The issue was fixed.
