### ISSUE TITLE
Differences between npm packages and github

### ISSUE THREAD

**Issue by jgradzki** [Synerise/synerise-design#11]
Hi,

seems that there are differences between npm packages and source code on github, for example translations for table are missing some keys

github:
https://github.com/Synerise/synerise-design/blob/92df028df2a2a2b60f10642dc0228308cd4cdff7/packages/components/core/src/i18n/en.json#L119-L131

npm package:
```
"TABLE": {
    "PAGINATION": {
        "ITEMS": "results",
        "GROUPS": "groups"
    },
    "SELECTED": "selected",
    "EMPTY_TEXT": "No data",
    "SELECTION_LIMIT_WARNING": "Selection limit has been reached.",
    "STAR_ROW_TOOLTIP": "Starred",
    "SELECT_ROW_TOOLTIP": "Select",
    "SELECT_ALL_TOOLTIP": "Select all",
    "SELECTION_OPTIONS": "Options",
    "COLUMN": {
        "SORT_AZ": "Sort a-z",
        "SORT_ZA": "Sort z-a",
        "SORT_ASCEND": "Sort ascending",
        "SORT_DESCEND": "Sort descending",
        "SORT_CLEAR": "Clear"
    },
    "INFINITE_SCROLL": {
        "ERROR": "Cannot load more items",
        "RETRY": "Retry",
        "NO_MORE_DATA": "There are no more items to load",
        "LOADING": "Loading more items",
        "BACK_TO_TOP": "Back to top"
    }
},
```

there are no translations for `COLUMN` or `INFINITE_SCROLL`. 

I suspect that there are much more differences, this can be misleading as github and storybook are main docs.

Can you update code on github?

**Comment by ofsajd** [comment]
Hi, currently we have some issues with synchronization between our original repo, and github. I'll handle it and let you know.

**Comment by ofsajd** [comment]
Hi, issue with synchronization has been fixed, and code on github was updated to latest version.
