### ISSUE TITLE
Having trouble using Menu with Dropdown

### ISSUE THREAD

**Issue by mattmalec** [Synerise/synerise-design#4]
Hi there! I'm having a bit of an issue creating a Menu with a dropdown (similar to withIconandLabel from the Storybook). 

When I click the Menu to open the dropdown, there's no opening animation, and modifying the "visible" property with a useState on the dropdown to false does not close the dropdown as expected. I'm also only able to click the icon instead of the entire menu item.

Is there a full example available that shows exactly how to do it? The one on the Github (https://github.com/Synerise/synerise-design/tree/master/packages/components/menu) is quite lacking and is leaving me stumped.

Any help would be appreciated.

Thanks in advance.

**Comment by mattmalec** [comment]
Update: I tried to set a model visible to true and then again to false. The menu did not animate open and it doesn't close. What am I doing wrong?

**Comment by mattmalec** [comment]
Another update: Seems like nothing in this library is working whatsoever. When I do something as simple as `message.success("Hello world")` using ds-message, there is no animation for the message popup and it never disappears.

**Comment by ofsajd** [comment]
Hi @mattmalec 

I apologise for the delay with the response. Below you can find the simplest example of usage of our `dropdown`, `menu`, and `message` components. 

```import React from 'react';
import {DSProvider} from '@synerise/ds-core';
import Button from '@synerise/ds-button';
import Menu from '@synerise/ds-menu';
import Dropdown from '@synerise/ds-dropdown';
import message from '@synerise/ds-message';

function App() {

  const showMessage = () => {
    message.success('Yeah!');
  }

  const menu = (
    <Menu asDropdownMenu>
      <Menu.Item onClick={showMessage}>Show Message</Menu.Item>
      <Menu.Item>Option #2</Menu.Item>
      <Menu.Item>Option #3</Menu.Item>
      <Menu.Item>Option #4</Menu.Item>
      <Menu.Item>Option #5</Menu.Item>
    </Menu>
  ) 
  return (
    <div className="App" style={{display: 'flex', alignItems: 'center', justifyContent: 'center', width: '100%', height: '100%', position: 'absolute'}}>
     <DSProvider>
      <Dropdown overlay={menu}>
      <Button type='primary'>Toogle</Button>
      </Dropdown>
     </DSProvider>
    </div>
  );
}

export default App;
```

Except of that, you should remember to add to your dependencies: `antd@4.8.0`, `styled-components` and `react-intl` in the same way as we show in our documentation: https://design.synerise.com/develop/.

I hope it will help you resolve your problems. If not, please let me know, and if you can share your code with us.

**Comment by mattmalec** [comment]
Thank you for your response. I've tried this exact code you've provided and the "Yeah!" message doesn't disappear. Like my previous comment, it just pops up without an animation. I'm using the latest versions of the dependencies you mentioned.

**Comment by ofsajd** [comment]
Please try to use antd in version `4.7.0`, this is the version what we used in current version of components.

**Comment by mattmalec** [comment]
Everything is working! 

I'm surprised that's what caused the problem. Maybe the required antd version should be detailed in the documentation :)

Thanks for the help!
