### ISSUE TITLE
Migration react-intl to react-i18next

### ISSUE THREAD

**Issue by jgradzki** [Synerise/synerise-design#7]
Hi,

I want to ask what were the reasons for choosing react-intl and ask if you would consider change to react-i18next.

In our project we are using react-i18next and we want to use Synerise Design which requires react-intl, forcing us to have two dependencies for internalization.

I made some key features comparison:

||**react-intl**|**react-i18next**|
| :-: | :-: | :-: |
|Documentation|- [react-intl](https://formatjs.io/docs/react-intl)<br />- [format-js](https://formatjs.io/docs/getting-started/installation)|- [react-i18next](https://react.i18next.com/)<br />- [i18next](https://www.i18next.com/)|
|Documentation quality and clarity (1-10)|4|8|
|Examples|[Link](https://github.com/formatjs/formatjs/tree/main/packages/react-intl/examples)|[Link](https://github.com/i18next/react-i18next/tree/master/example)|
|Translation Component|**Yes**|**Yes**|
|HOC|**Yes**|**Yes**|
|Hook|**Yes**|**Yes**|
|Nested messages|[No](https://formatjs.io/docs/react-intl/upgrade-guide-2x#flatten-messages-object)<br>(need to [flat](https://github.com/hughsk/flat) messages object)|[**Yes**](https://www.i18next.com/translation-function/essentials#accessing-keys)|
|Argument/Params|[**Yes**](https://formatjs.io/docs/core-concepts/icu-syntax#simple-argument)|[**Yes**](https://www.i18next.com/translation-function/interpolation#basic)|
|Object arguments|No|[**Yes**](https://www.i18next.com/translation-function/interpolation#working-with-data-models)|
|Default value|[**Yes**](https://formatjs.io/docs/getting-started/message-declaration/)|[**Yes**](https://www.i18next.com/translation-function/essentials#passing-a-default-value)|
|Multiple fallback keys|No|[**Yes**](https://www.i18next.com/principles/fallback#calling-with-fallback-keys)|
|Date/Currency/Number Formatting|[**Yes**](https://formatjs.io/docs/core-concepts/icu-syntax#formatted-argument)|[**Yes <br />(allows own formatting)**](https://www.i18next.com/translation-function/formatting)|
|Custom formatting|No|[**Yes**](https://www.i18next.com/translation-function/formatting)|
|Namespaces|No|[**Yes**](https://www.i18next.com/principles/namespaces)<br />([Multiple Translation Files](https://react.i18next.com/guides/multiple-translation-files))|
|Plurals|[**Yes**](https://formatjs.io/docs/core-concepts/icu-syntax#plural-format)|[**Yes**](https://www.i18next.com/translation-function/plurals#plurals)<br />(argument name must be “count”)|
|Select/Context|[**Yes**](https://formatjs.io/docs/core-concepts/icu-syntax#select-format)|[**Yes**](https://www.i18next.com/translation-function/context)|
|Objects and Arrays return|No|[**Yes**](https://www.i18next.com/translation-function/objects-and-arrays)|
|Lazy load translations|[**Yes**](https://github.com/formatjs/formatjs/tree/main/packages/react-intl/examples/StaticTypeSafetyAndCodeSplitting)|[**Yes**](https://www.i18next.com/how-to/add-or-load-translations#lazy-load-in-memory-translations)|
|Interpolation customization|No|[**Yes**](https://www.i18next.com/translation-function/interpolation#all-interpolation-options)|
|Caching|No|[**Yes**](https://www.i18next.com/how-to/caching)|
|Extracting translations|[**Yes**](https://formatjs.io/docs/getting-started/message-extraction)|[**Yes**](https://www.i18next.com/how-to/extracting-translations)|
|Online translations management / service|No|[**Yes (payed)**](https://locize.com/)|
|Plugins/Utils|<https://formatjs.io/docs/tooling/cli>|<https://www.i18next.com/overview/plugins-and-utils> <br /><https://www.i18next.com/principles/plugins>|

<br />

I have also noticed that you are using "FormattedMessage" but [docs](https://formatjs.io/docs/guides/advanced-usage#imperative-apis) recommend using [Imperative API](https://formatjs.io/docs/react-intl/api) for better performance.
This is also supported by react-i18next: <https://react.i18next.com/latest/usetranslation-hook> 
  <https://react.i18next.com/latest/withtranslation-hoc>

The downside (or in my opinion its advantage) i18next requires to make own implementation for formatting (e.g. dates), but it gives more options and customization (you can implement any formatting you will need).
With i18next i would suggest using date-fns for date formatting.

You are sometimes using day.js which kind of doubles same logic of formatting, this can be unified with i18next.

**Comment by ofsajd** [comment]
Hi Jan, thank you for your analysis. We used the react-intl in synerise-design becouse we use it in our platform. In that moment there is no plan to move to other intl tool.

**Comment by jgradzki** [comment]
Thanks for reply
